# Generated by Django 3.2.4 on 2021-06-10 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_rename_idade_teste_idade_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
